---
title: "Lab05"
author: "Michael Varnerin"
date: "December 1, 2017"
output: html_document
---

#Data Management
```{r}
#Load in Library
library(tidyverse)

#Set Up Variables
all_states <- map_data("state")
congress <- read.csv("womenincongress.csv")

#Convert State -> Region, then Merge
names(congress)[2] <- "region"
stateData <- merge(all_states, congress, by = "region")

#Create repProp
stateData <- mutate(stateData, repProp = (representatives/total))

#HousePlot Showing Proportion
housePlot <- ggplot()+geom_polygon(data=stateData,aes(x=long, y=lat, group = group, fill = repProp),color="grey50")+coord_map()+labs(x="",y="",title="Women in the House")+theme_classic()+ theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.ticks.x = element_blank(),axis.text.x = element_blank())+scale_fill_gradient(name="Female Representatives",low="whitesmoke",high="darkred", guide = guide_colorbar(title.position = "bottom"))

#Load in 2012 Election Data
electionData <- read.csv("2012.csv")

#State -> Region, Merge
names(electionData)[1] <- "region"

#Setting Up Obama and Romney's Percentage by State
electionData$ObamaPerc <- electionData$ObamaVotes/(electionData$ObamaVotes+electionData$RomneyVotes+electionData$JohnsonVotes+electionData$SteinVotes)
electionData$RomneyPerc <- electionData$RomneyVotes/(electionData$ObamaVotes+electionData$RomneyVotes+electionData$JohnsonVotes+electionData$SteinVotes)
electionData <- merge(all_states,electionData,by="region")

#South Election Plot
south <- filter(electionData, region %in% tolower(c("Delaware", "Florida", "Georgia", "Maryland", "North Carolina", "South Carolina", "Virginia", "District of Columbia", "West Virginia", "Alabama", "Kentucky", "Mississippi", "Tennessee", "Arkansas", "Louisiana", "Oklahoma", "Texas")))
SElectionPlot <- ggplot()+geom_polygon(data=south,aes(x=long, y=lat, group = group, fill=ObamaPerc),color="grey50")+coord_map()+labs(x="",y="",title="2012 Election Results")+theme_classic()+ theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.ticks.x = element_blank(),axis.text.x = element_blank()) + scale_fill_gradient2(name="Obama's Percenatage",low="red",mid="white",high="blue",midpoint=.5)
```

#Plots
```{r}
#Women in the House Plot
housePlot

#Southeast Senate Election Results Plot
SElectionPlot
```

